-- ABURTO TEAM community: isolated from Raíz Noble's commercial CRM.
CREATE SCHEMA IF NOT EXISTS aburto_team;
CREATE TABLE IF NOT EXISTS aburto_team.members (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 email text NOT NULL UNIQUE CHECK (length(email) <= 254),
 display_name text NOT NULL CHECK (length(display_name) BETWEEN 2 AND 60),
 bio text NOT NULL DEFAULT '' CHECK (length(bio) <= 240),
 role text NOT NULL DEFAULT 'member' CHECK (role IN ('member','moderator','coach','admin')),
 founding boolean NOT NULL DEFAULT false,
 status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended')),
 joined_at timestamptz NOT NULL DEFAULT now(),
 last_seen timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS aburto_team.login_codes (
 email text PRIMARY KEY,
 code_hash text NOT NULL,
 sent_at timestamptz NOT NULL DEFAULT now(),
 expires_at timestamptz NOT NULL,
 attempts int NOT NULL DEFAULT 0,
 requests int NOT NULL DEFAULT 1,
 first_request_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS aburto_team.rate_limits (
 bucket text PRIMARY KEY,
 period_start timestamptz NOT NULL DEFAULT now(),
 count int NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS aburto_team.sessions (
 token_hash text PRIMARY KEY,
 member_id uuid NOT NULL REFERENCES aburto_team.members(id) ON DELETE CASCADE,
 created_at timestamptz NOT NULL DEFAULT now(),
 expires_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS team_sessions_member ON aburto_team.sessions(member_id);
CREATE TABLE IF NOT EXISTS aburto_team.channels (
 slug text PRIMARY KEY CHECK (slug ~ '^[a-z0-9-]+$'),
 title text NOT NULL,
 description text NOT NULL DEFAULT '',
 category text NOT NULL DEFAULT 'COMUNIDAD',
 access text NOT NULL DEFAULT 'all' CHECK (access IN ('all','founding','coaching','staff')),
 sort_order int NOT NULL DEFAULT 0,
 locked boolean NOT NULL DEFAULT false
);
CREATE TABLE IF NOT EXISTS aburto_team.channel_members (
 channel_slug text NOT NULL REFERENCES aburto_team.channels(slug) ON DELETE CASCADE,
 member_id uuid NOT NULL REFERENCES aburto_team.members(id) ON DELETE CASCADE,
 added_by uuid REFERENCES aburto_team.members(id) ON DELETE SET NULL,
 PRIMARY KEY(channel_slug,member_id)
);
CREATE TABLE IF NOT EXISTS aburto_team.messages (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 channel_slug text NOT NULL REFERENCES aburto_team.channels(slug) ON DELETE CASCADE,
 member_id uuid NOT NULL REFERENCES aburto_team.members(id),
 body text NOT NULL CHECK (length(body) BETWEEN 1 AND 2000),
 created_at timestamptz NOT NULL DEFAULT now(),
 deleted_at timestamptz,
 pinned boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS team_messages_feed ON aburto_team.messages(channel_slug,id DESC);
CREATE TABLE IF NOT EXISTS aburto_team.audit_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 actor_id uuid REFERENCES aburto_team.members(id) ON DELETE SET NULL,
 action text NOT NULL,
 target text NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO aburto_team.channels (slug,title,description,category,access,sort_order) VALUES
('bienvenida','bienvenida','Empieza aquí. Conoce las reglas y presenta tu objetivo.','INICIO','all',10),
('general','general','Conversaciones del ABURTO TEAM.','COMUNIDAD','all',20),
('presentaciones','presentaciones','Comparte tu nombre y qué estás trabajando.','COMUNIDAD','all',30),
('entrenamiento','entrenamiento','Técnica, disciplina y progreso.','ENTRENAMIENTO','all',40),
('nutricion','nutricion','Hábitos y alimentación sin consejos médicos.','ENTRENAMIENTO','all',50),
('posing','posing','Práctica y preguntas sobre poses.','ENTRENAMIENTO','all',60),
('competencia','competencia','Preparación, experiencias y eventos.','ENTRENAMIENTO','all',70),
('founding','founding-members','Espacio exclusivo para Founding Members verificados.','EXCLUSIVOS','founding',80),
('coaching','coaching-privado','Canal privado para clientes invitados.','EXCLUSIVOS','coaching',90),
('staff','staff','Moderación y coordinación interna.','ADMINISTRACIÓN','staff',100)
ON CONFLICT (slug) DO NOTHING;
