import {libraryProducts,libraryUrl} from './library.js';
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function buildLibraryEmail(record,token){
  const en=record.language==='en',test=record.kind==='Prueba',gift=record.kind==='Cortesía';
  const products=libraryProducts(record.product,record.language),name=record.product==='starter-pack'?'Starter Pack':products[0].name;
  const label=en?(test?'DELIVERY TEST · NO CHARGE':gift?'COMPLIMENTARY COPY':'PURCHASE CONFIRMED'):(test?'PRUEBA DE ENTREGA · SIN CARGO':gift?'CORTESÍA DE ANDRÉS ABURTO':'COMPRA CONFIRMADA');
  const subject=en?`${test?'Delivery test — ':''}Your ${name} is ready`:`${test?'Prueba de entrega — ':''}Tu acceso a ${name} ya está listo`;
  const greeting=en?`Hello${record.name?', '+record.name:''}.`:`Hola${record.name?', '+record.name:''}.`;
  const intro=en?(test?'Your test copy is ready.':gift?'Andrés Aburto is sharing this complimentary copy with you.':'Thank you for your purchase. Your payment has been confirmed.'):(test?'Tu copia de prueba ya está lista.':gift?'Andrés Aburto te comparte esta copia de cortesía.':'Gracias por tu compra. Tu pago ha sido confirmado.');
  const help=en?'Open your personal library with the button below. You do not need a Google account. Before downloading, read and accept the privacy notice and personal-use agreement. Do not share your private link or files.':'Entra a tu biblioteca con el botón. No necesitas una cuenta de Google: funciona con Gmail, iCloud, Outlook, Yahoo y otros correos. Antes de descargar, lee y acepta el aviso de privacidad y el acuerdo de uso personal. No compartas tu enlace privado ni los archivos.';
  const follow=test?(en?'Reply to confirm whether this email arrived in your inbox or spam, and whether you could download all the books.':'Responde para confirmar si este correo llegó a la bandeja principal o a spam, y si pudiste descargar los libros.') :gift?(en?'After seven days, we would love your honest feedback.':'Después de siete días, nos encantará conocer tu experiencia honesta: qué te ayudó y qué podríamos mejorar.'):(en?'Reply to this email if you need help.':'Responde a este correo si necesitas ayuda con el acceso.');
  const url=libraryUrl(token),button=en?'OPEN MY LIBRARY →':'ABRIR MI BIBLIOTECA →';
  const text=[greeting,'',intro,products.map(p=>p.name).join(' · '),'',button+': '+url,'',help,'',follow,...(gift?['https://www.aburtoprocoach.com/#resenas-productos']:[]),'','Andrés Aburto · Pro Coach'].join('\n');
  const html=`<!doctype html><html lang="${en?'en':'es-MX'}"><body style="margin:0;background:#080808;font-family:Arial,sans-serif"><table role="presentation" width="100%"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="100%" style="max-width:640px;background:#101010;border:1px solid #333;border-top:6px solid #951f29"><tr><td style="padding:32px;color:#ddd;line-height:1.65"><img src="https://www.aburtoprocoach.com/assets/logo/aburto-original.png" width="180" alt="Aburto Pro Coach"><p style="color:#e9a1a1;font-size:12px;letter-spacing:1px">${label}</p><h1 style="color:white;line-height:1.1">${en?'YOUR LIBRARY<br>IS READY.':'TU BIBLIOTECA<br>YA ESTÁ LISTA.'}</h1><p>${esc(greeting)}</p><p>${esc(intro)}</p><p style="color:white;font-weight:bold">${products.map(p=>esc(p.name)).join('<br>')}</p><p><a href="${esc(url)}" style="display:inline-block;background:#951f29;padding:16px 24px;color:white;text-decoration:none;font-weight:bold;border-radius:6px">${button}</a></p><p style="background:#1c1c1c;padding:18px;font-size:13px">${esc(help)}</p><p>${esc(follow)}</p>${gift?'<p><a href="https://www.aburtoprocoach.com/#resenas-productos" style="color:#e9a1a1">'+(en?'Share my experience':'Compartir mi experiencia')+' →</a></p>':''}<p style="border-top:1px solid #333;padding-top:22px">Andrés Aburto · Pro Coach<br><span style="font-size:12px">${en?'Personal access · Reply if you need help':'Acceso personal · Responde si necesitas ayuda'}</span></p></td></tr></table></td></tr></table></body></html>`;
  return {subject,text,html};
}
